### ISSUE TITLE
Does not start in ubuntu

### ISSUE THREAD

**Issue by mkozioro** [zweicoder/WhatsApp-Desktop#8]
Hi.
I can't get it working on ubuntu. Here are the logs:

michal@michal-desktop:~$ /opt/supforwhatsapp/supforwhatsapp 
[15124:0203/001654:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[15124:0203/001654:ERROR:nw_shell.cc(335)] Error: Cannot find module 'auto-launch'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/tmp/.org.chromium.Chromium.ce7nJy/components/menus.js:3:18)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[15124:0203/001654:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'auto-launch'", source: module.js (329)
[15124:0203/001655:INFO:CONSOLE(0)] "Creating Application Cache with manifest https://web.whatsapp.com/wa.appcache", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001655:INFO:CONSOLE(0)] "Application Cache Checking event", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001655:INFO:CONSOLE(0)] "Application Cache Downloading event", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001655:INFO:CONSOLE(0)] "Application Cache Progress event (0 of 18) https://web.whatsapp.com/style_rtl_f6bcfd4890b344676bf7.css", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001655:INFO:CONSOLE(0)] "Application Cache Progress event (1 of 18) https://web.whatsapp.com/style_rtl.useable_6683271cd168da11d74f.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001655:INFO:CONSOLE(0)] "Application Cache Progress event (2 of 18) https://web.whatsapp.com/style.useable_65ba85607f89846e7c6e.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (3 of 18) https://web.whatsapp.com/img/favicon/1x/favicon.png", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (4 of 18) https://web.whatsapp.com/favicon-48x48.ico", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (5 of 18) https://web.whatsapp.com/vendor2_ab0adb35b4fa873889f0.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (6 of 18) https://web.whatsapp.com/favicon-64x64.ico", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (7 of 18) https://web.whatsapp.com/apple-touch-icon.png", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (8 of 18) https://web.whatsapp.com/unorm_61087420a42761ea568a.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (9 of 18) https://web.whatsapp.com/vendor1_312f29e5f848fcee03a2.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001656:INFO:CONSOLE(0)] "Application Cache Progress event (10 of 18) https://web.whatsapp.com/style_e42ffd016d0c3a1c036c.css", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (11 of 18) https://web.whatsapp.com/res/notification.mp3", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (12 of 18) https://web.whatsapp.com/main_f745f3644b9b55f7b33a.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (13 of 18) https://web.whatsapp.com/sprite_efc221f1dae96b8e4f43.css", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (14 of 18) https://web.whatsapp.com/progress_30397b77fffaa152d96f7c7f1b1fde43.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (15 of 18) https://web.whatsapp.com/favicon.ico", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (16 of 18) https://web.whatsapp.com/browsers_3f28609d75a32ce25cae69c43559ee5c.css", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (17 of 18) https://web.whatsapp.com/app_b8c64f9f65633c20e1b8.js", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Progress event (18 of 18) ", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)
[15124:0203/001657:INFO:CONSOLE(0)] "Application Cache Cached event", source: file:///tmp/.org.chromium.Chromium.ce7nJy/app.html (0)

**Comment by zweicoder** [comment]
Hi is it crashing after starting? It would be better if you could switch to the less buggy and more updated release at [this repo](https://github.com/zweicoder/AwesomeScripts/releases)
